eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  register-with-eureka: false
  fetch-registry: false
  instance:
    preferIpAddress: true
mybatis:
  configuration:
    #开启驼峰命名转换
    map-underscore-to-camel-case: true
  #mapper.xml文件位置
  mapper-locations: classpath*:mapper/*.xml
  check-config-location: true
  #对应mapper的实体类
  type-aliases-package: org.easymis.dap.catalog.mapper.**

#配置pagehelper
#pagehelper分页配置 第二种和第三种不需要 重点讲的第一种需要
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

spring:
  freemarker:
    template-loader-path: classpath:/templates/
    suffix: .html
    cache: false
    charset: utf-8
    request-context-attribute: request
  zipkin:
    base-url: http://192.168.230.1:9987/
  #这里把抽样百分比设置为1，即信息全部采集
  sleuth:
    sampler:
      probability: 1.0
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/easymis?characterEncoding=utf8&useSSL=false
    username: root
    password: root

  jpa:
    show-sql: true
    database: MYSQL
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  
  redis:
    host: 127.0.0.1
    port: 6379
    pool:
      max-idle: 8
      min-idle: 0
      max-active: 8
      max-wait: -1
logging:
  level:
    root: debug